# Generated by Django 4.1 on 2022-08-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_name", models.CharField(max_length=100)),
                ("client_org", models.CharField(max_length=500)),
                ("number", models.IntegerField()),
                ("sum", models.FloatField()),
                ("date", models.DateField()),
                ("service", models.CharField(max_length=500)),
            ],
            options={
                "unique_together": {("client_org", "number")},
            },
        ),
    ]
